### ISSUE TITLE
How to get reading

### ISSUE THREAD

**Issue by ghost** [klattimer/PyClickWheel#1]
Hi there,

thank you for your effort to convert the click.c code to a workable python service.

I have two small issues:
- The pyclickwheel.service is not starting automatically becuase pigpio is not installed as a service
- So I tried to boot up, `sudo pidpiod` and then `sudo systemctl start pyclickwheel`
- No error message so far

How do I now get the clickwheel (raw) readings?

I tried with a simle python key listener. Usb Keyboard is working fine, but nothing happens when I use the wheel.

Hope that you have a hint for me :-).

Tobi

**Comment by klattimer** [comment]
You gotta up the sample rate on pigpio, I haven't got this 100% reliable yet.

**Comment by klattimer** [comment]
Also, I think I made a service file for pigpio which started early... Not sure, I was messing a lot but haven't touched it in a bit.

**Comment by ghost** [comment]
thank you for your quick reply.
I haven't managed to get it running so I decided for another solution:

I modified the original clickwheel.c script with some uinput module lines so the clickwheel is now a keyboard and I can use it on all applications.

**Comment by klattimer** [comment]
You know that was what I wanted to do originally, but then I settled on python for reasons of writing it really quick and letting me mess around with it. Do you want to link your code? I'd be interested to look at it.

**Comment by ghost** [comment]
Sure, here it is.

For the moment I only have coded the buttons. Will work on the wheel in the next days. If it works I will create a public Git repo and link it here.

**Comment by ghost** [comment]
you can find the repo now here: https://github.com/githubtobi/ipod-clickwheel-driver

I have added the wheel function and adjusted the sensivity.
